import 'dart:ui';

class ColorRes {
  static const Color transparent = Color(0x00000000);
  // static const Color crystalBlue = Color(0xff58AFFF);
  static const Color crystalBlue = Color(0xff28a9be);
  // static const Color darkSkyBlue = Color(0xff4D92E2);
  static const Color darkSkyBlue = Color(0xff28a9be);
  // static const Color havelockBlue = Color(0xff4E93E2);
  static const Color havelockBlue = Color(0x8028a9be);
  // static const Color tuftsBlue = Color(0xff4680CF);
  static const Color tuftsBlue = Color(0xff28a9be);
  // static const Color tuftsBlue100 = Color(0xff4378C8);
  static const Color tuftsBlue100 = Color(0xff28a9be);
  static const Color white = Color(0xffFFFFFF);
  static const Color cloud = Color(0xffC5C5C5);
  static const Color nobel = Color(0xffB3B3B3);
  static const Color silverChalice = Color(0xffACACAC);
  static const Color starDust = Color(0xff9B9B9B);
  static const Color grey = Color(0xff909090);
  static const Color battleshipGrey = Color(0xff848484);
  static const Color mediumGrey = Color(0xff7F7F7F);
  static const Color davyGrey = Color(0xff5B5B5B);
  static const Color charcoalGrey = Color(0xff414141);
  static const Color darkJungleGreen = Color(0xff202020);
  static const Color black = Color(0xff000000);
  static const Color pinkLace = Color(0xffFFDFDF);
  static const Color mercury = Color(0xffE6E6E6);
  static const Color blueLagoon = Color(0x77E6E8EB);
  static const Color lightGrey = Color(0xffDADADA);
  static const Color silver = Color(0xffC6C6C6);
  static const Color softPeach = Color(0xffEFEFEF);
  static const Color whiteSmoke = Color(0xffF4F4F4);
  static const Color aquaHaze = Color(0xffF3F3F3);
  static const Color greenWhite = Color(0xffEAEAEA);
  static const Color dawnPink = Color(0xffECECEC);
  static const Color snowDrift = Color(0xffF9F9F9);
  static const Color iceberg = Color(0xffDDEEFE);
  static const Color bittersweet = Color(0xffFF6D6D);
  static const Color lightRed = Color(0xffFF4848);
  static const Color ferrariRed = Color(0xffFF1616);
  static const Color irishGreen = Color(0xff008E1F);
  static const Color mediumGreen = Color(0xff00BE2A);
  static const Color fadedOrange = Color(0xffF0933E);
  static const Color mangoOrange = Color(0xffFF842B);
  static const Color seashell = Color(0xffF1F1F1);
  static const Color smokeyGrey = Color(0xff747474);
}
